(Adds) portalTargetSelector to Type
jossmac/react-toast-notifications pull request #157
Opened 2021-03-22 10:26 UTC by KasperAndersson

Missing since https://github.com/jossmac/react-toast-notifications/pull/151

2021-03-22 21:26 UTC, jossmac requested changes

2021-03-22 21:26 UTC, jossmac commented on index.d.ts
> +    portalTargetSelector: string;
This should be optional, right?

```suggestion
    portalTargetSelector?: string;
```

2021-03-23 08:14 UTC, KasperAndersson commented on index.d.ts
> +    portalTargetSelector: string;
Obv., sorry!

2021-03-23 22:28 UTC, jossmac approved these changes

2021-03-23 22:28 UTC, merged