Type fixing fo typescript project.
jossmac/react-toast-notifications pull request #161
Opened 2021-04-22 19:57 UTC by zhenyanghua

- Making `appearance` optional and default to `'info'`.
- Fix typing for typescript project when a custom toast element is provided.
- Fix cross platform build script by adding `cross-env`.

2021-04-22 22:50 UTC, jossmac requested changes
Thanks! Looks good, just unsure about the docs wording

2021-04-22 22:50 UTC, jossmac commented on README.md
> +| appearance                         | Only used when no custom toast components are provided. One of `success`, `error`, `warning`, `info`. |
> Only used when no custom toast components are provided.

I'm not sure this is quite right, you could provide a custom toast that consumes this prop. Prefer something like:

```suggestion
| appearance | Used by the default toast. One of `success`, `error`, `warning`, `info`. |
```

2021-04-23 00:20 UTC, zhenyanghua commented
All set. Thanks for the suggestion.

2021-04-23 00:33 UTC, jossmac approved these changes

2021-04-23 00:39 UTC, merged