Add newestOnTop prop on ToastProvider
jossmac/react-toast-notifications pull request #173
Opened 2021-07-02 14:07 UTC by ochomoswill

Add functionality to allow having the newest toast at the top of the stack

2021-07-04 21:25 UTC, jossmac requested changes

2021-07-04 21:25 UTC, jossmac commented on src/ToastProvider.js
> +  newestOnTop: boolean
Please add docs to the [README](https://github.com/jossmac/react-toast-notifications#toastprovider-props).

2021-07-04 21:28 UTC, jossmac commented on src/ToastProvider.js
> +  newestOnTop: boolean
Please update [types](https://github.com/jossmac/react-toast-notifications/blob/master/index.d.ts#L44).

2021-07-04 21:29 UTC, jossmac commented on src/ToastProvider.js
> +  newestOnTop: boolean
Please sort alphabetically, like the other props.

2021-07-04 21:31 UTC, jossmac requested changes
Looks good. A few things:
- Add docs to the [README](https://github.com/jossmac/react-toast-notifications#toastprovider-props).
- Update [types](https://github.com/jossmac/react-toast-notifications/blob/master/index.d.ts#L44).
- Sort alphabetically, like other props

2021-07-05 06:03 UTC, jossmac commented on src/ToastProvider.js
> +  // have the newest toast at the top of the stack
```suggestion
  // When true, insert new toasts at the top of the stack
```

2021-07-05 06:04 UTC, jossmac commented on README.md
> +| newestOnTop `boolean`                  | Default `false`. Whether to have the newest toast at the top or bottom of the toastStack.  |
```suggestion
| newestOnTop `boolean`                  | Default `false`. When true, insert new toasts at the top of the stack.  |
```

2021-07-05 06:05 UTC, jossmac commented on src/ToastProvider.js
> +  transitionDuration: number
```suggestion
  transitionDuration: number,
```

2021-07-05 06:05 UTC, jossmac commented on src/ToastProvider.js
> +    transitionDuration: 220
```suggestion
    transitionDuration: 220,
```

2021-07-05 06:06 UTC, ochomoswill commented on src/ToastProvider.js
> +  // have the newest toast at the top of the stack
Cool. That sounds good.

2021-07-05 06:48 UTC, jossmac approved these changes

2021-07-05 06:51 UTC, merged

2021-07-05 07:02 UTC, jossmac commented
Available from `2.5.0`